# Generated by Django 4.0.4 on 2022-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='blood_group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='floor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addstudent',
            name='hostel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
