# Generated by Django 4.0.4 on 2022-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_addadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addadmin',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addadmin',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addadmin',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
