# Generated by Django 4.0.4 on 2022-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_addadmin_full_name_alter_addadmin_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOuting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=25, null=True)),
                ('room_no', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=50)),
                ('outing_time', models.CharField(max_length=20)),
                ('in_time', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
    ]
