# Generated by Django 4.0.4 on 2022-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_studentleave_date_of_outing'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='date_of_outing',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentleave',
            name='date_of_comeing',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
