# Generated by Django 4.0.4 on 2022-04-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_studentleave_date_of_outing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
