# Generated by Django 4.0.4 on 2022-04-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_studentleave_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
