# Generated by Django 4.0.4 on 2022-04-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_leaveapprovel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddStudent',
        ),
    ]
