# Generated by Django 4.0.4 on 2022-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_first_name', models.CharField(max_length=50)),
                ('father_last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('blood_group', models.CharField(max_length=50, null=True)),
                ('college_name', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('hostel', models.CharField(max_length=50, null=True)),
                ('floor', models.CharField(max_length=50, null=True)),
                ('room_number', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False, verbose_name='Aproved')),
                ('Aaa', models.CharField(max_length=50, null=True)),
                ('Aab', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
