# Generated by Django 4.0.4 on 2022-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_studentleave_studentouting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleave',
            name='Aaa',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentouting',
            name='Aaa',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
