# Generated by Django 4.0.4 on 2022-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_studentleave_aaa_alter_studentouting_aaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('father_first_name', models.CharField(max_length=50)),
                ('father_last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('blood_group', models.CharField(max_length=50, null=True)),
                ('community', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('Aaa', models.CharField(max_length=50, null=True)),
                ('Aab', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddAdmin',
        ),
    ]
