# Generated by Django 4.0.4 on 2022-04-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_roomchange_new_room_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomChange',
        ),
    ]
